name: Echo env:My_NAME on std out.
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      env:
        MY_NAME: "Mona"
